CREATE USER 'USER_ADMIN'@'%';
GRANT ALL PRIVILEGES ON `secure\_cloud`.* TO 'USER_ADMIN'@'%' WITH GRANT OPTION;
SET PASSWORD FOR 'USER_ADMIN'@'%' = PASSWORD('eygdh3f8ug3ybjxi93uf48uh3ghv93jfj843jh834fuifh');