CREATE USER 'USER_TYPE_SELECT'@'%';
GRANT SELECT ON `secure\_cloud`.* TO 'USER_TYPE_SELECT'@'%';
SET PASSWORD FOR 'USER_TYPE_SELECT'@'%' = PASSWORD('q29xhg9gi3vcz93rkc01wjxb5gfy49j');

CREATE USER 'USER_TYPE_INSERT'@'%';
GRANT INSERT ON `secure\_cloud`.* TO 'USER_TYPE_INSERT'@'%';
SET PASSWORD FOR 'USER_TYPE_INSERT'@'%' = PASSWORD('zq274vcni03xnu83wkmxcbvy3o02nvu');

CREATE USER 'USER_TYPE_DELETE'@'%';
GRANT DELETE ON `secure\_cloud`.* TO 'USER_TYPE_DELETE'@'%';
SET PASSWORD FOR 'USER_TYPE_DELETE'@'%' = PASSWORD('1bz85gvc904lqky17hxh9940jvn48bx');

CREATE USER 'USER_TYPE_UPDATE'@'%';
GRANT UPDATE ON `secure\_cloud`.* TO 'USER_TYPE_UPDATE'@'%';
SET PASSWORD FOR 'USER_TYPE_UPDATE'@'%' = PASSWORD('3cxs9u3hfb1cm39bfjsok92js94cb4f');

CREATE USER 'USER_ADMIN'@'%';
GRANT ALL PRIVILEGES ON `secure\_cloud`.* TO 'USER_ADMIN'@'%' WITH GRANT OPTION;
SET PASSWORD FOR 'USER_ADMIN'@'%' = PASSWORD('10eygdh3f8ug3ybjxi93uf48uh3ghv93jfj843jh834fuifh');