private const QRY =
        [
            "INS_CRED" => "INSERT INTO `secure-cloud`.`users` (email, pass, `name`, surname, joined, 2FA, verified) VALUES (?, ?, ?, ?, CURDATE(), 0, 0)",
            "LOGIN" => "SELECT * FROM `secure-cloud`.`users` WHERE email = ?",
            "ACC_REC" => "INSERT INTO `secure-cloud`.`account_recovery` (id_user, htkn, expires) VALUES (?, ?, ADDTIME(NOW(), 1000))",
            "ID_FROM_EMAIL" => "SELECT id FROM `secure-cloud`.`users` WHERE email = ?",
            "EMAIL_FROM_ID" => "SELECT email FROM `secure-cloud`.`users` WHERE id = ?",
            "TKN_ROW" => "SELECT u.email, r.expires FROM `secure-cloud`.`account_recovery` AS r, `secure-cloud`.`users` AS u WHERE u.id = r.id_user AND r.htkn = ? AND r.expires > NOW()",
            "DEL_TKN" => "DELETE FROM `secure-cloud`.`account_recovery` WHERE htkn = ?",
            "CH_PASS" => "UPDATE `secure-cloud`.`users` SET pass = ? WHERE email = ?",
            "CH_PASS_ID" => "UPDATE `secure-cloud`.`users` SET pass = ? WHERE id = ?",
            "REM_DEL" => "DELETE FROM `secure-cloud`.`remember` WHERE htkn = ?",
            "REM_SEL" => "SELECT * FROM `secure-cloud`.`remember` WHERE htkn = ? AND expires > NOW()",
            "DEL_USER_WITH_EMAIL" => "DELETE FROM `secure-cloud`.`users` WHERE email = ?",
            "TSF_FILE" => "INSERT INTO `secure-cloud`.`transfers` (tdate, `type`, id_user, id_session, id_file) VALUES (NOW(), ?, ?, ?, ?)",
            "SET_2FA" => "UPDATE `secure-cloud`.`users` SET 2FA = ? WHERE id = ?",
            "GET_2FA" => "SELECT 2FA FROM `secure-cloud`.`users` WHERE id = ?",
            "DEL_FILE" => "UPDATE `secure-cloud`.`files` SET view = 0 WHERE idf = ?",
            "SEL_REF" => "SELECT ref FROM `secure-cloud`.`files` WHERE idf = ?",
            "IS_VER" => "SELECT verified FROM `secure-cloud`.`users` WHERE id = ?",
            "UPD_IS_VER" => "UPDATE `secure-cloud`.`users` SET verified = ? WHERE id = ?",
            "INS_TKN_VER" => "INSERT INTO `secure-cloud`.`account_verify` (id_user, htkn, expires) VALUES (?, ?, ADDTIME(NOW(), 10000))",
            "SEL_TKN_VER" => "SELECT id_user FROM `secure-cloud`.`account_verify` WHERE htkn = ?",
            "DEL_TKN_VER" => "DELETE FROM `secure-cloud`.`account_verify` WHERE id_user = ?",
            "INS_SESS" => "INSERT INTO `secure-cloud`.`sessions` (id, ip, client, os, device, last_time, session_status, id_user, rem_htkn) VALUES (?,?,?,?,?,NOW(),1,?,?)",
            "SEL_SESS" => "SELECT * FROM `secure-cloud`.`sessions` WHERE id = ? AND session_status = 1",
            "SEL_SESS_HTKN" => "SELECT * FROM `secure-cloud`.`sessions` WHERE rem_htkn = ? AND session_status = 1",
            "UPD_SESS" => "UPDATE `secure-cloud`.`sessions` SET last_time = NOW() WHERE id = ? AND session_status = 1",
            "EXP_SESS" => "UPDATE `secure-cloud`.`sessions` SET session_status = 0 WHERE id = ?",
            "SEL_SESS_ALL" => "SELECT * FROM `secure-cloud`.`sessions` WHERE id_user = ? ORDER BY session_status DESC, last_time DESC",
            "SEL_SESS_STATUS" => "SELECT session_status FROM `secure-cloud`.`sessions` WHERE id = ?",
            "INS_FILE_DATA" => "INSERT INTO `secure-cloud`.`files` (idf, fname, ref, size, id_user, mime) VALUES (?,?,?,?,?,?)",
            "SEL_FILEIDS" => "SELECT idf FROM `secure-cloud`.`files` WHERE view = 1 AND id_user = ?",
            "SEL_FILE" => "SELECT f.ref AS ref, f.fname AS nam, f.size AS siz, f.mime AS mme, t.tdate AS dat FROM `secure-cloud`.`files` f, `secure-cloud`.`transfers` t WHERE f.idf = t.id_file AND f.idf = ?",
            "TSF_TBL" => "SELECT f.fname AS filename, f.size AS filesize, t.tdate AS transfer_date, s.ip AS ip_address, t.type AS type FROM files f, transfers t, sessions s WHERE t.id_file = f.idf AND t.id_session = s.id AND t.id_user = ? GROUP BY t.id ORDER BY t.tdate DESC",
            "SEL_USER_BY_ID" => "SELECT `name`, surname, email, notes, 2FA, joined FROM  `secure-cloud`.`users` WHERE id = ?",
            "UPD_USER_BY_ID" => "UPDATE `secure-cloud`.`users` SET `name` = ?, surname = ?, notes = ? WHERE id = ?",
            "SEL_PASS" => "SELECT pass FROM `secure-cloud`.`users` WHERE id = ?",
            "SEL_PLAN" => "SELECT p.name AS PLAN_NAME, p.gb AS SIZE FROM users u, plans p WHERE u.id_plan = p.id AND u.id = ?",
            "SEL_ID_FROM_PLANAME" => "SELECT id FROM plans WHERE name = ?",
            "UPD_PLAN" => "UPDATE `secure-cloud`.`users` SET `id_plan` = ? WHERE id = ?",
            "GET_USED_SPACE" => "SELECT SUM(size) AS size FROM `secure-cloud`.`files` WHERE view = 1 AND id_user = ?",
            "DEL_USER" => "DELETE FROM `secure-cloud`.`users` WHERE id = ?",
            "DEL_TRANSFERS" => "DELETE FROM `secure-cloud`.`transfers` WHERE id_user = ?",
            "DEL_FILES" => "DELETE FROM `secure-cloud`.`files` WHERE id_user = ?",
            "DEL_SESSIONS" => "DELETE FROM `secure-cloud`.`sessions` WHERE id_user = ?"
        ];